#
FROM ubuntu:22.04 AS base
#
ENV DEBIAN_FRONTEND=noninteractive
#
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update

RUN apt-get install -y apt-utils
RUN apt-get install -y build-essential
RUN apt-get install -y wget vim curl
RUN apt-get install -y libcurl4-openssl-dev libssl-dev
#
RUN apt install -y python3.9
RUN apt install -y python3-pip
RUN pip install --upgrade pip
#
RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash - && apt-get install -y nodejs
RUN npm install -g npm@9.6.5
RUN npm install -g lighthouse
#
# COPY ./google-chrome-stable_current_amd64.deb /google-chrome-stable_current_amd64.deb
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get -f install -y ./google-chrome-stable_current_amd64.deb
RUN echo "Chrome: " && google-chrome --version

#
RUN mkdir -p /tmp/screenshots/

#docker build -t 10.10.11.140:5000/shopastro:base-python . -f Dockerfile_base_python